# Basic Information
title: Wenlin Zhang
position: Ph.D. Candidate
affiliation: City University of Hong Kong
affiliation_link: https://www.cityu.edu.hk/
email: wl.z(at)my.cityu.edu.hk
lang: en-US

# Search Engine Optimization
keywords: Large Language Models, Search Agent, Recommender System, Agentic RAG
description: Wenlin Zhang is a Ph.D. candidate at City University of Hong Kong.
canonical: https://wlzhang2020.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=qyr7C8oAAAAJ&hl=zh-CN
cv_link: assets/files/WenlinZhang_CV.pdf
github_link: https://github.com/wlzhang2020

# Images
avatar: ./assets/img/profile.png
favicon: ./assets/img/favicon-w.png
favicon_dark: ./assets/img/favicon-w.png

# Theme options
enable_footnote: true
auto_dark_mode: false
font: "Serif"

# Google Analytics ID
# google_analytics:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
